# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmtKVbhnAK_doQMIaXGXCcF-_eIpsmGU
"""

# Import pandas to handle data tables
import pandas as pd

# Import numpy for math calculations
import numpy as np

# Import tools for splitting data and measuring model accuracy
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

print("Libraries imported successfully!")

# Read your CSV file into a table format (DataFrame) named 'df'
df = pd.read_csv('/content/test_Y3wMUE5_7gLdaTN-selected-columns python.csv')

# Display the first 5 rows of your dataset
print("First 5 rows of your dataset:")
print(df.head())

# Fill missing text categories with the most frequent choice (mode)
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)
df['Self_Employed'].fillna(df['Self_Employed'].mode()[0], inplace=True)

# Fill missing number values (like Loan Amount) with the middle value (median)
df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median(), inplace=True)

print("Missing values cleaned successfully!")

# Convert text columns into numeric codes
df['Gender'] = df['Gender'].astype('category').cat.codes
df['Married'] = df['Married'].astype('category').cat.codes
df['Dependents'] = df['Dependents'].astype('category').cat.codes
df['Education'] = df['Education'].astype('category').cat.codes
df['Self_Employed'] = df['Self_Employed'].astype('category').cat.codes

print("Text categories successfully converted to numbers!")

# 'X' represents the input clues (income, education, marital status, etc.)
X = df[['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'Loan_Amount_Term']]

# 'y' represents what we want the model to predict (LoanAmount)
y = df['LoanAmount']

print("Inputs and target variables defined!")

# Split data: 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training rows: {X_train.shape[0]}")
print(f"Testing rows: {X_test.shape[0]}")

# Choose the Random Forest Regressor algorithm
model = RandomForestRegressor(random_state=42)

# Train the model to learn the patterns from the data
model.fit(X_train, y_train)

print("Model training completed successfully!")

# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate performance metrics
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("Model Performance Evaluation:")
print(f"R-squared Score (Accuracy fit): {r2:.2f}")
print(f"Root Mean Squared Error (Average error margin): {rmse:.2f}")